// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guest_groups.sql

package sqlc

import (
	"context"
)

const countGuestGroups = `-- name: CountGuestGroups :one
SELECT COUNT(*) FROM guest_groups
`

func (q *Queries) CountGuestGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuestGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuestGroup = `-- name: CreateGuestGroup :execlastid

INSERT INTO guest_groups (name, description) VALUES (?, ?)
`

type CreateGuestGroupParams struct {
	Name        string
	Description string
}

// Query tabel guest_groups - docs/plan/guest-groups/PLAN.md T2.
//
// Berkas TERPISAH dari guests.sql, satu berkas per tabel (pola modul content
// yang punya 7 berkas .sql dalam satu direktori). sqlc.yaml TIDAK berubah:
// konfigurasinya memetakan direktori queries -> package per modul, jadi
// berkas baru di sini otomatis ikut ter-generate (§1.3).
//
// Query yang menyentuh tabel `guests` (CountGuestsByGroupID,
// CountGuestsGroupedByGroup) TETAP tinggal di guests.sql - berkas ini hanya
// untuk tabel guest_groups.
func (q *Queries) CreateGuestGroup(ctx context.Context, arg CreateGuestGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createGuestGroup, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteGuestGroup = `-- name: DeleteGuestGroup :exec
DELETE FROM guest_groups WHERE id = ?
`

func (q *Queries) DeleteGuestGroup(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteGuestGroup, id)
	return err
}

const getGuestGroupByID = `-- name: GetGuestGroupByID :one
SELECT id, name, description, created_at, updated_at FROM guest_groups WHERE id = ? LIMIT 1
`

func (q *Queries) GetGuestGroupByID(ctx context.Context, id uint64) (GuestGroup, error) {
	row := q.db.QueryRowContext(ctx, getGuestGroupByID, id)
	var i GuestGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuestGroupByName = `-- name: GetGuestGroupByName :one
SELECT id, name, description, created_at, updated_at FROM guest_groups WHERE name = ? LIMIT 1
`

// GetGuestGroupByName adalah penjaga UNIQUE di sisi service (D5) - dicek
// SEBELUM tulis supaya admin menerima "nama sudah dipakai" yang enak dibaca,
// bukan error duplicate key mentah dari MySQL. Preseden: ErrUsernameTaken di
// modul auth.
func (q *Queries) GetGuestGroupByName(ctx context.Context, name string) (GuestGroup, error) {
	row := q.db.QueryRowContext(ctx, getGuestGroupByName, name)
	var i GuestGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuestGroups = `-- name: ListGuestGroups :many
SELECT id, name, description, created_at, updated_at FROM guest_groups ORDER BY name ASC LIMIT ? OFFSET ?
`

type ListGuestGroupsParams struct {
	Limit  int32
	Offset int32
}

// ORDER BY name ASC (bukan created_at DESC seperti guests): daftar group
// dipakai untuk MENCARI satu group di dropdown & tabel, jadi urutan abjad
// yang bisa ditebak lebih berguna daripada yang terbaru di atas.
func (q *Queries) ListGuestGroups(ctx context.Context, arg ListGuestGroupsParams) ([]GuestGroup, error) {
	rows, err := q.db.QueryContext(ctx, listGuestGroups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuestGroup
	for rows.Next() {
		var i GuestGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuestGroup = `-- name: UpdateGuestGroup :exec
UPDATE guest_groups SET name = ?, description = ? WHERE id = ?
`

type UpdateGuestGroupParams struct {
	Name        string
	Description string
	ID          uint64
}

func (q *Queries) UpdateGuestGroup(ctx context.Context, arg UpdateGuestGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateGuestGroup, arg.Name, arg.Description, arg.ID)
	return err
}
