// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countCheckedInGuests = `-- name: CountCheckedInGuests :one
SELECT COUNT(*) FROM guests WHERE checked_in_at IS NOT NULL
`

func (q *Queries) CountCheckedInGuests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckedInGuests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuestsByGroupID = `-- name: CountGuestsByGroupID :one
SELECT COUNT(*) FROM guests WHERE group_id = ?
`

// CountGuestsByGroupID adalah penjaga K4: dipanggil TEPAT SEBELUM menghapus
// group supaya hitungannya sesegar mungkin, dan angkanya ikut disebut di
// pesan penolakan ("masih dipakai N tamu"). Ber-index lewat
// idx_guests_group_id (migration 000016).
func (q *Queries) CountGuestsByGroupID(ctx context.Context, groupID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuestsByGroupID, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuestsFiltered = `-- name: CountGuestsFiltered :one
SELECT COUNT(*) FROM guests
WHERE (? IS NULL OR rsvp_status = ?)
  AND (CAST(? AS UNSIGNED) = 0 OR rsvp_status != 'pending')
  AND (? IS NULL OR invitation_type = ?)
  AND (? IS NULL OR souvenir_type = ?)
  AND (? IS NULL OR group_id = ?)
  AND (? IS NULL OR name LIKE ? OR phone LIKE ? OR email LIKE ?)
`

type CountGuestsFilteredParams struct {
	Status         NullGuestsRsvpStatus
	RespondedOnly  int64
	InvitationType NullGuestsInvitationType
	SouvenirType   NullGuestsSouvenirType
	GroupID        sql.NullInt64
	Q              sql.NullString
}

func (q *Queries) CountGuestsFiltered(ctx context.Context, arg CountGuestsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuestsFiltered,
		arg.Status,
		arg.Status,
		arg.RespondedOnly,
		arg.InvitationType,
		arg.InvitationType,
		arg.SouvenirType,
		arg.SouvenirType,
		arg.GroupID,
		arg.GroupID,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuestsGroupedByGender = `-- name: CountGuestsGroupedByGender :many
SELECT gender, COUNT(*) AS total FROM guests WHERE gender IS NOT NULL GROUP BY gender
`

type CountGuestsGroupedByGenderRow struct {
	Gender NullGuestsGender
	Total  int64
}

func (q *Queries) CountGuestsGroupedByGender(ctx context.Context) ([]CountGuestsGroupedByGenderRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedByGender)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedByGenderRow
	for rows.Next() {
		var i CountGuestsGroupedByGenderRow
		if err := rows.Scan(&i.Gender, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGuestsGroupedByGroup = `-- name: CountGuestsGroupedByGroup :many
SELECT group_id, COUNT(*) AS total FROM guests WHERE group_id IS NOT NULL GROUP BY group_id
`

type CountGuestsGroupedByGroupRow struct {
	GroupID sql.NullInt64
	Total   int64
}

// CountGuestsGroupedByGroup mengisi kolom "Jumlah tamu" SELURUH baris di
// halaman Group lewat SATU query - bukan satu COUNT per baris group (yang
// itu N+1). Pola persis CountGuestsGroupedByStatus di atas.
// WHERE group_id IS NOT NULL: tamu lama yang belum bergroup (K2/§2.6) tidak
// punya baris hasil untuk dipetakan ke group mana pun.
func (q *Queries) CountGuestsGroupedByGroup(ctx context.Context) ([]CountGuestsGroupedByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedByGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedByGroupRow
	for rows.Next() {
		var i CountGuestsGroupedByGroupRow
		if err := rows.Scan(&i.GroupID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGuestsGroupedByInvitationType = `-- name: CountGuestsGroupedByInvitationType :many
SELECT invitation_type, COUNT(*) AS total FROM guests GROUP BY invitation_type
`

type CountGuestsGroupedByInvitationTypeRow struct {
	InvitationType GuestsInvitationType
	Total          int64
}

func (q *Queries) CountGuestsGroupedByInvitationType(ctx context.Context) ([]CountGuestsGroupedByInvitationTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedByInvitationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedByInvitationTypeRow
	for rows.Next() {
		var i CountGuestsGroupedByInvitationTypeRow
		if err := rows.Scan(&i.InvitationType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGuestsGroupedBySide = `-- name: CountGuestsGroupedBySide :many
SELECT side, COUNT(*) AS total FROM guests GROUP BY side
`

type CountGuestsGroupedBySideRow struct {
	Side  GuestsSide
	Total int64
}

func (q *Queries) CountGuestsGroupedBySide(ctx context.Context) ([]CountGuestsGroupedBySideRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedBySide)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedBySideRow
	for rows.Next() {
		var i CountGuestsGroupedBySideRow
		if err := rows.Scan(&i.Side, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGuestsGroupedBySouvenirType = `-- name: CountGuestsGroupedBySouvenirType :many
SELECT souvenir_type, COUNT(*) AS total FROM guests GROUP BY souvenir_type
`

type CountGuestsGroupedBySouvenirTypeRow struct {
	SouvenirType GuestsSouvenirType
	Total        int64
}

func (q *Queries) CountGuestsGroupedBySouvenirType(ctx context.Context) ([]CountGuestsGroupedBySouvenirTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedBySouvenirType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedBySouvenirTypeRow
	for rows.Next() {
		var i CountGuestsGroupedBySouvenirTypeRow
		if err := rows.Scan(&i.SouvenirType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGuestsGroupedByStatus = `-- name: CountGuestsGroupedByStatus :many
SELECT rsvp_status, COUNT(*) AS total, CAST(COALESCE(SUM(attending_count), 0) AS UNSIGNED) AS total_pax FROM guests GROUP BY rsvp_status
`

type CountGuestsGroupedByStatusRow struct {
	RsvpStatus GuestsRsvpStatus
	Total      int64
	TotalPax   int64
}

// CountGuestsGroupedByStatus juga menghasilkan total_pax (SUM attending_count)
// digabung ke query yang sama (PLAN.md dashboard-wa-rsvp keputusan #16) -
// satu scan menghasilkan jumlah undangan DAN jumlah orang sekaligus.
func (q *Queries) CountGuestsGroupedByStatus(ctx context.Context) ([]CountGuestsGroupedByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedByStatusRow
	for rows.Next() {
		var i CountGuestsGroupedByStatusRow
		if err := rows.Scan(&i.RsvpStatus, &i.Total, &i.TotalPax); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGuest = `-- name: CreateGuest :execlastid
INSERT INTO guests (name, phone, side, group_id, token, rsvp_status, gender, invitation_type, souvenir_type, email, address, notes, is_expected_attending)
VALUES (?, ?, ?, ?, ?, 'pending', ?, ?, ?, ?, ?, ?, ?)
`

type CreateGuestParams struct {
	Name                string
	Phone               string
	Side                GuestsSide
	GroupID             sql.NullInt64
	Token               string
	Gender              NullGuestsGender
	InvitationType      GuestsInvitationType
	SouvenirType        GuestsSouvenirType
	Email               string
	Address             sql.NullString
	Notes               sql.NullString
	IsExpectedAttending bool
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createGuest,
		arg.Name,
		arg.Phone,
		arg.Side,
		arg.GroupID,
		arg.Token,
		arg.Gender,
		arg.InvitationType,
		arg.SouvenirType,
		arg.Email,
		arg.Address,
		arg.Notes,
		arg.IsExpectedAttending,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteGuest = `-- name: DeleteGuest :exec
DELETE FROM guests WHERE id = ?
`

func (q *Queries) DeleteGuest(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteGuest, id)
	return err
}

const getCheckinSummary = `-- name: GetCheckinSummary :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN checked_in_at IS NOT NULL AND side = 'groom' THEN 1 ELSE 0 END), 0) AS UNSIGNED) AS arrived_groom,
  CAST(COALESCE(SUM(CASE WHEN checked_in_at IS NOT NULL AND side = 'bride' THEN 1 ELSE 0 END), 0) AS UNSIGNED) AS arrived_bride,
  CAST(COALESCE(SUM(CASE WHEN checked_in_at IS NOT NULL THEN 1 ELSE 0 END), 0) AS UNSIGNED) AS arrived_total,
  CAST(COALESCE(SUM(CASE WHEN checked_in_at IS NOT NULL THEN attending_count ELSE 0 END), 0) AS UNSIGNED) AS arrived_pax,
  COUNT(*) AS total_guests
FROM guests
`

type GetCheckinSummaryRow struct {
	ArrivedGroom int64
	ArrivedBride int64
	ArrivedTotal int64
	ArrivedPax   int64
	TotalGuests  int64
}

// GetCheckinSummary menghasilkan SELURUH angka kartu ringkasan gate dalam
// SATU kali scan tabel - bukan 4 query COUNT terpisah, pola yang sama
// dengan CountGuestsGroupedByStatus di atas.
//
// arrived_* menghitung BARIS TAMU (undangan), bukan orang, konsisten dengan
// `total_guests` sebagai penyebutnya. arrived_pax terpisah dan menjumlahkan
// attending_count: itu jumlah orang yang DIJANJIKAN tamu saat RSVP, bukan
// hasil hitung kepala di pintu - sistem ini memang tidak merekamnya
// (docs/plan/scan-checkin-gate/PLAN.md §3.2). Label di UI harus jujur soal itu.
func (q *Queries) GetCheckinSummary(ctx context.Context) (GetCheckinSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getCheckinSummary)
	var i GetCheckinSummaryRow
	err := row.Scan(
		&i.ArrivedGroom,
		&i.ArrivedBride,
		&i.ArrivedTotal,
		&i.ArrivedPax,
		&i.TotalGuests,
	)
	return i, err
}

const getGuestByID = `-- name: GetGuestByID :one
SELECT id, name, phone, side, token, rsvp_status, rsvp_responded_at, created_at, updated_at, gender, invitation_type, souvenir_type, email, address, notes, attending_count, is_expected_attending, checked_in_at, group_id FROM guests WHERE id = ? LIMIT 1
`

func (q *Queries) GetGuestByID(ctx context.Context, id uint64) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuestByID, id)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Side,
		&i.Token,
		&i.RsvpStatus,
		&i.RsvpRespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.InvitationType,
		&i.SouvenirType,
		&i.Email,
		&i.Address,
		&i.Notes,
		&i.AttendingCount,
		&i.IsExpectedAttending,
		&i.CheckedInAt,
		&i.GroupID,
	)
	return i, err
}

const getGuestByToken = `-- name: GetGuestByToken :one
SELECT id, name, phone, side, token, rsvp_status, rsvp_responded_at, created_at, updated_at, gender, invitation_type, souvenir_type, email, address, notes, attending_count, is_expected_attending, checked_in_at, group_id FROM guests WHERE token = ? LIMIT 1
`

func (q *Queries) GetGuestByToken(ctx context.Context, token string) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuestByToken, token)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Side,
		&i.Token,
		&i.RsvpStatus,
		&i.RsvpRespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.InvitationType,
		&i.SouvenirType,
		&i.Email,
		&i.Address,
		&i.Notes,
		&i.AttendingCount,
		&i.IsExpectedAttending,
		&i.CheckedInAt,
		&i.GroupID,
	)
	return i, err
}

const listCheckedInGuests = `-- name: ListCheckedInGuests :many
SELECT id, name, side, souvenir_type, attending_count, checked_in_at FROM guests
WHERE checked_in_at IS NOT NULL
ORDER BY checked_in_at DESC
LIMIT ? OFFSET ?
`

type ListCheckedInGuestsParams struct {
	Limit  int32
	Offset int32
}

type ListCheckedInGuestsRow struct {
	ID             uint64
	Name           string
	Side           GuestsSide
	SouvenirType   GuestsSouvenirType
	AttendingCount uint8
	CheckedInAt    sql.NullTime
}

// ListCheckedInGuests: daftar tamu yang SUDAH tiba, terbaru di atas -
// menu "Tamu Masuk" milik petugas gate. Kolomnya disebut satu per satu
// (bukan SELECT *) supaya baris hasil TIDAK membawa phone/email/address/
// notes/token ke jalur yang diakses akun petugas; lihat CheckinSummaryDTO
// di application/dto.go untuk alasan keamanannya.
func (q *Queries) ListCheckedInGuests(ctx context.Context, arg ListCheckedInGuestsParams) ([]ListCheckedInGuestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCheckedInGuests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCheckedInGuestsRow
	for rows.Next() {
		var i ListCheckedInGuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Side,
			&i.SouvenirType,
			&i.AttendingCount,
			&i.CheckedInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestsFiltered = `-- name: ListGuestsFiltered :many
SELECT id, name, phone, side, token, rsvp_status, rsvp_responded_at, created_at, updated_at, gender, invitation_type, souvenir_type, email, address, notes, attending_count, is_expected_attending, checked_in_at, group_id FROM guests
WHERE (? IS NULL OR rsvp_status = ?)
  AND (CAST(? AS UNSIGNED) = 0 OR rsvp_status != 'pending')
  AND (? IS NULL OR invitation_type = ?)
  AND (? IS NULL OR souvenir_type = ?)
  AND (? IS NULL OR group_id = ?)
  AND (? IS NULL OR name LIKE ? OR phone LIKE ? OR email LIKE ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListGuestsFilteredParams struct {
	Status         NullGuestsRsvpStatus
	RespondedOnly  int64
	InvitationType NullGuestsInvitationType
	SouvenirType   NullGuestsSouvenirType
	GroupID        sql.NullInt64
	Q              sql.NullString
	Limit          int32
	Offset         int32
}

func (q *Queries) ListGuestsFiltered(ctx context.Context, arg ListGuestsFilteredParams) ([]Guest, error) {
	rows, err := q.db.QueryContext(ctx, listGuestsFiltered,
		arg.Status,
		arg.Status,
		arg.RespondedOnly,
		arg.InvitationType,
		arg.InvitationType,
		arg.SouvenirType,
		arg.SouvenirType,
		arg.GroupID,
		arg.GroupID,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guest
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Side,
			&i.Token,
			&i.RsvpStatus,
			&i.RsvpRespondedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.InvitationType,
			&i.SouvenirType,
			&i.Email,
			&i.Address,
			&i.Notes,
			&i.AttendingCount,
			&i.IsExpectedAttending,
			&i.CheckedInAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRsvpResponses = `-- name: ListRecentRsvpResponses :many
SELECT name, rsvp_status, attending_count, rsvp_responded_at FROM guests
WHERE rsvp_responded_at IS NOT NULL
ORDER BY rsvp_responded_at DESC
LIMIT 5
`

type ListRecentRsvpResponsesRow struct {
	Name            string
	RsvpStatus      GuestsRsvpStatus
	AttendingCount  uint8
	RsvpRespondedAt sql.NullTime
}

// ListRecentRsvpResponses dipakai kartu "Aktivitas RSVP terbaru" di Ringkasan
// (PLAN.md dashboard-wa-rsvp §3.2) - rsvp_responded_at sudah diisi setiap
// kali status berubah tapi belum pernah ditampilkan di UI mana pun.
func (q *Queries) ListRecentRsvpResponses(ctx context.Context) ([]ListRecentRsvpResponsesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRsvpResponses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentRsvpResponsesRow
	for rows.Next() {
		var i ListRecentRsvpResponsesRow
		if err := rows.Scan(
			&i.Name,
			&i.RsvpStatus,
			&i.AttendingCount,
			&i.RsvpRespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGuestCheckedIn = `-- name: MarkGuestCheckedIn :execrows
UPDATE guests SET checked_in_at = NOW() WHERE id = ? AND checked_in_at IS NULL
`

// MarkGuestCheckedIn adalah UPDATE BERSYARAT, bukan baca-lalu-tulis
// (docs/plan/scan-checkin-gate/PLAN.md D5). `AND checked_in_at IS NULL`
// membuat dua petugas yang memindai QR yang sama pada detik yang sama tidak
// saling menimpa jam kedatangan, tanpa perlu transaksi.
// :execrows (BUKAN :exec) disengaja: jumlah baris terpengaruh itulah yang
// membedakan "baru saja check-in" (1) dari "sudah check-in sebelumnya" (0) -
// persis informasi yang diminta K3.
func (q *Queries) MarkGuestCheckedIn(ctx context.Context, id uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markGuestCheckedIn, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateGuest = `-- name: UpdateGuest :exec
UPDATE guests SET name = ?, phone = ?, side = ?, group_id = ?, gender = ?, invitation_type = ?, souvenir_type = ?, email = ?, address = ?, notes = ?, is_expected_attending = ?
WHERE id = ?
`

type UpdateGuestParams struct {
	Name                string
	Phone               string
	Side                GuestsSide
	GroupID             sql.NullInt64
	Gender              NullGuestsGender
	InvitationType      GuestsInvitationType
	SouvenirType        GuestsSouvenirType
	Email               string
	Address             sql.NullString
	Notes               sql.NullString
	IsExpectedAttending bool
	ID                  uint64
}

func (q *Queries) UpdateGuest(ctx context.Context, arg UpdateGuestParams) error {
	_, err := q.db.ExecContext(ctx, updateGuest,
		arg.Name,
		arg.Phone,
		arg.Side,
		arg.GroupID,
		arg.Gender,
		arg.InvitationType,
		arg.SouvenirType,
		arg.Email,
		arg.Address,
		arg.Notes,
		arg.IsExpectedAttending,
		arg.ID,
	)
	return err
}

const updateGuestRsvpStatusByToken = `-- name: UpdateGuestRsvpStatusByToken :exec
UPDATE guests SET rsvp_status = ?, attending_count = ?, rsvp_responded_at = NOW()
WHERE token = ?
`

type UpdateGuestRsvpStatusByTokenParams struct {
	RsvpStatus     GuestsRsvpStatus
	AttendingCount uint8
	Token          string
}

func (q *Queries) UpdateGuestRsvpStatusByToken(ctx context.Context, arg UpdateGuestRsvpStatusByTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateGuestRsvpStatusByToken, arg.RsvpStatus, arg.AttendingCount, arg.Token)
	return err
}
