// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countGuestsFiltered = `-- name: CountGuestsFiltered :one
SELECT COUNT(*) FROM guests
WHERE (? IS NULL OR rsvp_status = ?)
  AND (CAST(? AS UNSIGNED) = 0 OR rsvp_status != 'pending')
  AND (? IS NULL OR invitation_type = ?)
  AND (? IS NULL OR souvenir_type = ?)
  AND (? IS NULL OR name LIKE ? OR phone LIKE ? OR email LIKE ?)
`

type CountGuestsFilteredParams struct {
	Status         NullGuestsRsvpStatus
	RespondedOnly  int64
	InvitationType NullGuestsInvitationType
	SouvenirType   NullGuestsSouvenirType
	Q              sql.NullString
}

func (q *Queries) CountGuestsFiltered(ctx context.Context, arg CountGuestsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuestsFiltered,
		arg.Status,
		arg.Status,
		arg.RespondedOnly,
		arg.InvitationType,
		arg.InvitationType,
		arg.SouvenirType,
		arg.SouvenirType,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuestsGroupedByGender = `-- name: CountGuestsGroupedByGender :many
SELECT gender, COUNT(*) AS total FROM guests WHERE gender IS NOT NULL GROUP BY gender
`

type CountGuestsGroupedByGenderRow struct {
	Gender NullGuestsGender
	Total  int64
}

func (q *Queries) CountGuestsGroupedByGender(ctx context.Context) ([]CountGuestsGroupedByGenderRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedByGender)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedByGenderRow
	for rows.Next() {
		var i CountGuestsGroupedByGenderRow
		if err := rows.Scan(&i.Gender, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGuestsGroupedByInvitationType = `-- name: CountGuestsGroupedByInvitationType :many
SELECT invitation_type, COUNT(*) AS total FROM guests GROUP BY invitation_type
`

type CountGuestsGroupedByInvitationTypeRow struct {
	InvitationType GuestsInvitationType
	Total          int64
}

func (q *Queries) CountGuestsGroupedByInvitationType(ctx context.Context) ([]CountGuestsGroupedByInvitationTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedByInvitationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedByInvitationTypeRow
	for rows.Next() {
		var i CountGuestsGroupedByInvitationTypeRow
		if err := rows.Scan(&i.InvitationType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGuestsGroupedBySide = `-- name: CountGuestsGroupedBySide :many
SELECT side, COUNT(*) AS total FROM guests GROUP BY side
`

type CountGuestsGroupedBySideRow struct {
	Side  GuestsSide
	Total int64
}

func (q *Queries) CountGuestsGroupedBySide(ctx context.Context) ([]CountGuestsGroupedBySideRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedBySide)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedBySideRow
	for rows.Next() {
		var i CountGuestsGroupedBySideRow
		if err := rows.Scan(&i.Side, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGuestsGroupedBySouvenirType = `-- name: CountGuestsGroupedBySouvenirType :many
SELECT souvenir_type, COUNT(*) AS total FROM guests GROUP BY souvenir_type
`

type CountGuestsGroupedBySouvenirTypeRow struct {
	SouvenirType GuestsSouvenirType
	Total        int64
}

func (q *Queries) CountGuestsGroupedBySouvenirType(ctx context.Context) ([]CountGuestsGroupedBySouvenirTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedBySouvenirType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedBySouvenirTypeRow
	for rows.Next() {
		var i CountGuestsGroupedBySouvenirTypeRow
		if err := rows.Scan(&i.SouvenirType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGuestsGroupedByStatus = `-- name: CountGuestsGroupedByStatus :many
SELECT rsvp_status, COUNT(*) AS total, CAST(COALESCE(SUM(attending_count), 0) AS UNSIGNED) AS total_pax FROM guests GROUP BY rsvp_status
`

type CountGuestsGroupedByStatusRow struct {
	RsvpStatus GuestsRsvpStatus
	Total      int64
	TotalPax   int64
}

// CountGuestsGroupedByStatus juga menghasilkan total_pax (SUM attending_count)
// digabung ke query yang sama (PLAN.md dashboard-wa-rsvp keputusan #16) -
// satu scan menghasilkan jumlah undangan DAN jumlah orang sekaligus.
func (q *Queries) CountGuestsGroupedByStatus(ctx context.Context) ([]CountGuestsGroupedByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countGuestsGroupedByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGuestsGroupedByStatusRow
	for rows.Next() {
		var i CountGuestsGroupedByStatusRow
		if err := rows.Scan(&i.RsvpStatus, &i.Total, &i.TotalPax); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGuest = `-- name: CreateGuest :execlastid
INSERT INTO guests (name, phone, side, token, rsvp_status, gender, invitation_type, souvenir_type, email, address, notes, is_expected_attending)
VALUES (?, ?, ?, ?, 'pending', ?, ?, ?, ?, ?, ?, ?)
`

type CreateGuestParams struct {
	Name                string
	Phone               string
	Side                GuestsSide
	Token               string
	Gender              NullGuestsGender
	InvitationType      GuestsInvitationType
	SouvenirType        GuestsSouvenirType
	Email               string
	Address             sql.NullString
	Notes               sql.NullString
	IsExpectedAttending bool
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createGuest,
		arg.Name,
		arg.Phone,
		arg.Side,
		arg.Token,
		arg.Gender,
		arg.InvitationType,
		arg.SouvenirType,
		arg.Email,
		arg.Address,
		arg.Notes,
		arg.IsExpectedAttending,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteGuest = `-- name: DeleteGuest :exec
DELETE FROM guests WHERE id = ?
`

func (q *Queries) DeleteGuest(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteGuest, id)
	return err
}

const getGuestByID = `-- name: GetGuestByID :one
SELECT id, name, phone, side, token, rsvp_status, rsvp_responded_at, created_at, updated_at, gender, invitation_type, souvenir_type, email, address, notes, attending_count, is_expected_attending FROM guests WHERE id = ? LIMIT 1
`

func (q *Queries) GetGuestByID(ctx context.Context, id uint64) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuestByID, id)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Side,
		&i.Token,
		&i.RsvpStatus,
		&i.RsvpRespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.InvitationType,
		&i.SouvenirType,
		&i.Email,
		&i.Address,
		&i.Notes,
		&i.AttendingCount,
		&i.IsExpectedAttending,
	)
	return i, err
}

const getGuestByToken = `-- name: GetGuestByToken :one
SELECT id, name, phone, side, token, rsvp_status, rsvp_responded_at, created_at, updated_at, gender, invitation_type, souvenir_type, email, address, notes, attending_count, is_expected_attending FROM guests WHERE token = ? LIMIT 1
`

func (q *Queries) GetGuestByToken(ctx context.Context, token string) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuestByToken, token)
	var i Guest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Side,
		&i.Token,
		&i.RsvpStatus,
		&i.RsvpRespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.InvitationType,
		&i.SouvenirType,
		&i.Email,
		&i.Address,
		&i.Notes,
		&i.AttendingCount,
		&i.IsExpectedAttending,
	)
	return i, err
}

const listGuestsFiltered = `-- name: ListGuestsFiltered :many
SELECT id, name, phone, side, token, rsvp_status, rsvp_responded_at, created_at, updated_at, gender, invitation_type, souvenir_type, email, address, notes, attending_count, is_expected_attending FROM guests
WHERE (? IS NULL OR rsvp_status = ?)
  AND (CAST(? AS UNSIGNED) = 0 OR rsvp_status != 'pending')
  AND (? IS NULL OR invitation_type = ?)
  AND (? IS NULL OR souvenir_type = ?)
  AND (? IS NULL OR name LIKE ? OR phone LIKE ? OR email LIKE ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListGuestsFilteredParams struct {
	Status         NullGuestsRsvpStatus
	RespondedOnly  int64
	InvitationType NullGuestsInvitationType
	SouvenirType   NullGuestsSouvenirType
	Q              sql.NullString
	Limit          int32
	Offset         int32
}

func (q *Queries) ListGuestsFiltered(ctx context.Context, arg ListGuestsFilteredParams) ([]Guest, error) {
	rows, err := q.db.QueryContext(ctx, listGuestsFiltered,
		arg.Status,
		arg.Status,
		arg.RespondedOnly,
		arg.InvitationType,
		arg.InvitationType,
		arg.SouvenirType,
		arg.SouvenirType,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guest
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Side,
			&i.Token,
			&i.RsvpStatus,
			&i.RsvpRespondedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.InvitationType,
			&i.SouvenirType,
			&i.Email,
			&i.Address,
			&i.Notes,
			&i.AttendingCount,
			&i.IsExpectedAttending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRsvpResponses = `-- name: ListRecentRsvpResponses :many
SELECT name, rsvp_status, attending_count, rsvp_responded_at FROM guests
WHERE rsvp_responded_at IS NOT NULL
ORDER BY rsvp_responded_at DESC
LIMIT 5
`

type ListRecentRsvpResponsesRow struct {
	Name            string
	RsvpStatus      GuestsRsvpStatus
	AttendingCount  uint8
	RsvpRespondedAt sql.NullTime
}

// ListRecentRsvpResponses dipakai kartu "Aktivitas RSVP terbaru" di Ringkasan
// (PLAN.md dashboard-wa-rsvp §3.2) - rsvp_responded_at sudah diisi setiap
// kali status berubah tapi belum pernah ditampilkan di UI mana pun.
func (q *Queries) ListRecentRsvpResponses(ctx context.Context) ([]ListRecentRsvpResponsesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRsvpResponses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentRsvpResponsesRow
	for rows.Next() {
		var i ListRecentRsvpResponsesRow
		if err := rows.Scan(
			&i.Name,
			&i.RsvpStatus,
			&i.AttendingCount,
			&i.RsvpRespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuest = `-- name: UpdateGuest :exec
UPDATE guests SET name = ?, phone = ?, side = ?, gender = ?, invitation_type = ?, souvenir_type = ?, email = ?, address = ?, notes = ?, is_expected_attending = ?
WHERE id = ?
`

type UpdateGuestParams struct {
	Name                string
	Phone               string
	Side                GuestsSide
	Gender              NullGuestsGender
	InvitationType      GuestsInvitationType
	SouvenirType        GuestsSouvenirType
	Email               string
	Address             sql.NullString
	Notes               sql.NullString
	IsExpectedAttending bool
	ID                  uint64
}

func (q *Queries) UpdateGuest(ctx context.Context, arg UpdateGuestParams) error {
	_, err := q.db.ExecContext(ctx, updateGuest,
		arg.Name,
		arg.Phone,
		arg.Side,
		arg.Gender,
		arg.InvitationType,
		arg.SouvenirType,
		arg.Email,
		arg.Address,
		arg.Notes,
		arg.IsExpectedAttending,
		arg.ID,
	)
	return err
}

const updateGuestRsvpStatusByToken = `-- name: UpdateGuestRsvpStatusByToken :exec
UPDATE guests SET rsvp_status = ?, attending_count = ?, rsvp_responded_at = NOW()
WHERE token = ?
`

type UpdateGuestRsvpStatusByTokenParams struct {
	RsvpStatus     GuestsRsvpStatus
	AttendingCount uint8
	Token          string
}

func (q *Queries) UpdateGuestRsvpStatusByToken(ctx context.Context, arg UpdateGuestRsvpStatusByTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateGuestRsvpStatusByToken, arg.RsvpStatus, arg.AttendingCount, arg.Token)
	return err
}
