// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wedding_wishes.sql

package sqlc

import (
	"context"
	"time"
)

const countWeddingWishes = `-- name: CountWeddingWishes :one
SELECT COUNT(*) FROM wedding_wishes
`

func (q *Queries) CountWeddingWishes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWeddingWishes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWeddingWish = `-- name: CreateWeddingWish :execlastid

INSERT INTO wedding_wishes (guest_id, message) VALUES (?, ?)
`

type CreateWeddingWishParams struct {
	GuestID uint64
	Message string
}

// Query tabel wedding_wishes - docs/plan/wedding-wish/PLAN.md T3.
//
// Berkas TERPISAH, satu berkas per tabel (pola guest_groups.sql).
// sqlc.yaml TIDAK berubah: konfigurasinya memetakan direktori queries ->
// package per modul, jadi berkas baru di sini otomatis ikut ter-generate.
//
// JOIN ke guests SAH karena intra-modul (D5): tabel wedding_wishes dimiliki
// modul guest yang sama. Nama pengirim diambil live lewat JOIN, bukan
// snapshot, supaya perbaikan nama tamu di admin langsung tercermin di
// undangan.
func (q *Queries) CreateWeddingWish(ctx context.Context, arg CreateWeddingWishParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createWeddingWish, arg.GuestID, arg.Message)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteWeddingWish = `-- name: DeleteWeddingWish :exec
DELETE FROM wedding_wishes WHERE id = ?
`

func (q *Queries) DeleteWeddingWish(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteWeddingWish, id)
	return err
}

const getWeddingWishByGuestID = `-- name: GetWeddingWishByGuestID :one
SELECT id, guest_id, message, is_hidden, created_at, updated_at FROM wedding_wishes WHERE guest_id = ? LIMIT 1
`

// GetWeddingWishByGuestID dipakai DUA jalur: penjaga "sekali saja" di
// SubmitWish, dan ResolveByToken (mengisi HasWish + WishMessage). Lookup pada
// UNIQUE key, O(1).
func (q *Queries) GetWeddingWishByGuestID(ctx context.Context, guestID uint64) (WeddingWish, error) {
	row := q.db.QueryRowContext(ctx, getWeddingWishByGuestID, guestID)
	var i WeddingWish
	err := row.Scan(
		&i.ID,
		&i.GuestID,
		&i.Message,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeddingWishByID = `-- name: GetWeddingWishByID :one
SELECT id, guest_id, message, is_hidden, created_at, updated_at FROM wedding_wishes WHERE id = ? LIMIT 1
`

// GetWeddingWishByID adalah penjaga 404 sebelum SetHidden/Delete, supaya
// admin menerima "tidak ditemukan" dan bukan 200 palsu atas baris yang
// tidak ada.
func (q *Queries) GetWeddingWishByID(ctx context.Context, id uint64) (WeddingWish, error) {
	row := q.db.QueryRowContext(ctx, getWeddingWishByID, id)
	var i WeddingWish
	err := row.Scan(
		&i.ID,
		&i.GuestID,
		&i.Message,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicWeddingWishes = `-- name: ListPublicWeddingWishes :many
SELECT w.id, w.message, w.created_at, g.name AS guest_name, g.side AS guest_side
FROM wedding_wishes w
JOIN guests g ON g.id = w.guest_id
WHERE w.is_hidden = FALSE
ORDER BY w.created_at DESC
LIMIT ?
`

type ListPublicWeddingWishesRow struct {
	ID        uint64
	Message   string
	CreatedAt time.Time
	GuestName string
	GuestSide GuestsSide
}

// Filter + sort keduanya terlayani idx_wedding_wishes_visible
// (is_hidden, created_at).
func (q *Queries) ListPublicWeddingWishes(ctx context.Context, limit int32) ([]ListPublicWeddingWishesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicWeddingWishes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicWeddingWishesRow
	for rows.Next() {
		var i ListPublicWeddingWishesRow
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.CreatedAt,
			&i.GuestName,
			&i.GuestSide,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeddingWishesAdmin = `-- name: ListWeddingWishesAdmin :many
SELECT w.id, w.guest_id, w.message, w.is_hidden, w.created_at,
       g.name AS guest_name, g.side AS guest_side
FROM wedding_wishes w
JOIN guests g ON g.id = w.guest_id
ORDER BY w.created_at DESC
LIMIT ? OFFSET ?
`

type ListWeddingWishesAdminParams struct {
	Limit  int32
	Offset int32
}

type ListWeddingWishesAdminRow struct {
	ID        uint64
	GuestID   uint64
	Message   string
	IsHidden  bool
	CreatedAt time.Time
	GuestName string
	GuestSide GuestsSide
}

// Admin melihat SEMUA termasuk yang disembunyikan - itu justru gunanya.
func (q *Queries) ListWeddingWishesAdmin(ctx context.Context, arg ListWeddingWishesAdminParams) ([]ListWeddingWishesAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listWeddingWishesAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWeddingWishesAdminRow
	for rows.Next() {
		var i ListWeddingWishesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.GuestID,
			&i.Message,
			&i.IsHidden,
			&i.CreatedAt,
			&i.GuestName,
			&i.GuestSide,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWeddingWishHidden = `-- name: SetWeddingWishHidden :exec
UPDATE wedding_wishes SET is_hidden = ? WHERE id = ?
`

type SetWeddingWishHiddenParams struct {
	IsHidden bool
	ID       uint64
}

func (q *Queries) SetWeddingWishHidden(ctx context.Context, arg SetWeddingWishHiddenParams) error {
	_, err := q.db.ExecContext(ctx, setWeddingWishHidden, arg.IsHidden, arg.ID)
	return err
}
