// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: whatsapp.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countSendLogs = `-- name: CountSendLogs :one
SELECT COUNT(*) FROM whatsapp_send_logs
`

func (q *Queries) CountSendLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSendLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSendLogByID = `-- name: GetSendLogByID :one
SELECT id, guest_id, guest_name, phone, qr_payload, couple_name, event_date_label, status, error_message, sent_at, created_at, attending_count FROM whatsapp_send_logs WHERE id = ? LIMIT 1
`

func (q *Queries) GetSendLogByID(ctx context.Context, id uint64) (WhatsappSendLog, error) {
	row := q.db.QueryRowContext(ctx, getSendLogByID, id)
	var i WhatsappSendLog
	err := row.Scan(
		&i.ID,
		&i.GuestID,
		&i.GuestName,
		&i.Phone,
		&i.QrPayload,
		&i.CoupleName,
		&i.EventDateLabel,
		&i.Status,
		&i.ErrorMessage,
		&i.SentAt,
		&i.CreatedAt,
		&i.AttendingCount,
	)
	return i, err
}

const getWhatsAppConfig = `-- name: GetWhatsAppConfig :one
SELECT id, message_template, is_enabled, updated_at FROM whatsapp_config WHERE id = 1 LIMIT 1
`

func (q *Queries) GetWhatsAppConfig(ctx context.Context) (WhatsappConfig, error) {
	row := q.db.QueryRowContext(ctx, getWhatsAppConfig)
	var i WhatsappConfig
	err := row.Scan(
		&i.ID,
		&i.MessageTemplate,
		&i.IsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSendLog = `-- name: InsertSendLog :execlastid
INSERT INTO whatsapp_send_logs (guest_id, guest_name, phone, qr_payload, couple_name, event_date_label, attending_count, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSendLogParams struct {
	GuestID        uint64
	GuestName      string
	Phone          string
	QrPayload      string
	CoupleName     string
	EventDateLabel string
	AttendingCount uint8
	Status         WhatsappSendLogsStatus
}

func (q *Queries) InsertSendLog(ctx context.Context, arg InsertSendLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSendLog,
		arg.GuestID,
		arg.GuestName,
		arg.Phone,
		arg.QrPayload,
		arg.CoupleName,
		arg.EventDateLabel,
		arg.AttendingCount,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listSendLogs = `-- name: ListSendLogs :many
SELECT id, guest_id, guest_name, phone, qr_payload, couple_name, event_date_label, status, error_message, sent_at, created_at, attending_count FROM whatsapp_send_logs ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListSendLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSendLogs(ctx context.Context, arg ListSendLogsParams) ([]WhatsappSendLog, error) {
	rows, err := q.db.QueryContext(ctx, listSendLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WhatsappSendLog
	for rows.Next() {
		var i WhatsappSendLog
		if err := rows.Scan(
			&i.ID,
			&i.GuestID,
			&i.GuestName,
			&i.Phone,
			&i.QrPayload,
			&i.CoupleName,
			&i.EventDateLabel,
			&i.Status,
			&i.ErrorMessage,
			&i.SentAt,
			&i.CreatedAt,
			&i.AttendingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSendLogStatus = `-- name: UpdateSendLogStatus :exec
UPDATE whatsapp_send_logs SET status = ?, error_message = ?, sent_at = ? WHERE id = ?
`

type UpdateSendLogStatusParams struct {
	Status       WhatsappSendLogsStatus
	ErrorMessage sql.NullString
	SentAt       sql.NullTime
	ID           uint64
}

func (q *Queries) UpdateSendLogStatus(ctx context.Context, arg UpdateSendLogStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSendLogStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.SentAt,
		arg.ID,
	)
	return err
}

const updateWhatsAppConfig = `-- name: UpdateWhatsAppConfig :exec
UPDATE whatsapp_config SET message_template = ?, is_enabled = ? WHERE id = 1
`

type UpdateWhatsAppConfigParams struct {
	MessageTemplate string
	IsEnabled       bool
}

func (q *Queries) UpdateWhatsAppConfig(ctx context.Context, arg UpdateWhatsAppConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateWhatsAppConfig, arg.MessageTemplate, arg.IsEnabled)
	return err
}
