// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agenda_events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAgendaEvent = `-- name: CreateAgendaEvent :execlastid
INSERT INTO agenda_events (event_label, time_label, venue_name, venue_address, city, maps_url, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAgendaEventParams struct {
	EventLabel   string
	TimeLabel    string
	VenueName    string
	VenueAddress sql.NullString
	City         string
	MapsUrl      string
	SortOrder    int32
}

func (q *Queries) CreateAgendaEvent(ctx context.Context, arg CreateAgendaEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAgendaEvent,
		arg.EventLabel,
		arg.TimeLabel,
		arg.VenueName,
		arg.VenueAddress,
		arg.City,
		arg.MapsUrl,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteAgendaEvent = `-- name: DeleteAgendaEvent :exec
DELETE FROM agenda_events WHERE id = ?
`

func (q *Queries) DeleteAgendaEvent(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteAgendaEvent, id)
	return err
}

const getAgendaEvent = `-- name: GetAgendaEvent :one
SELECT id, event_label, time_label, venue_name, venue_address, city, maps_url, sort_order FROM agenda_events WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgendaEvent(ctx context.Context, id uint64) (AgendaEvent, error) {
	row := q.db.QueryRowContext(ctx, getAgendaEvent, id)
	var i AgendaEvent
	err := row.Scan(
		&i.ID,
		&i.EventLabel,
		&i.TimeLabel,
		&i.VenueName,
		&i.VenueAddress,
		&i.City,
		&i.MapsUrl,
		&i.SortOrder,
	)
	return i, err
}

const listAgendaEvents = `-- name: ListAgendaEvents :many
SELECT id, event_label, time_label, venue_name, venue_address, city, maps_url, sort_order FROM agenda_events ORDER BY sort_order ASC
`

func (q *Queries) ListAgendaEvents(ctx context.Context) ([]AgendaEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAgendaEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgendaEvent
	for rows.Next() {
		var i AgendaEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventLabel,
			&i.TimeLabel,
			&i.VenueName,
			&i.VenueAddress,
			&i.City,
			&i.MapsUrl,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgendaEvent = `-- name: UpdateAgendaEvent :exec
UPDATE agenda_events SET event_label=?, time_label=?, venue_name=?, venue_address=?, city=?, maps_url=?, sort_order=?
WHERE id = ?
`

type UpdateAgendaEventParams struct {
	EventLabel   string
	TimeLabel    string
	VenueName    string
	VenueAddress sql.NullString
	City         string
	MapsUrl      string
	SortOrder    int32
	ID           uint64
}

func (q *Queries) UpdateAgendaEvent(ctx context.Context, arg UpdateAgendaEventParams) error {
	_, err := q.db.ExecContext(ctx, updateAgendaEvent,
		arg.EventLabel,
		arg.TimeLabel,
		arg.VenueName,
		arg.VenueAddress,
		arg.City,
		arg.MapsUrl,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
