// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gallery_photos.sql

package sqlc

import (
	"context"
)

const createGalleryPhoto = `-- name: CreateGalleryPhoto :execlastid
INSERT INTO gallery_photos (photo_url, thumb_url, sort_order)
VALUES (?, ?, ?)
`

type CreateGalleryPhotoParams struct {
	PhotoUrl  string
	ThumbUrl  string
	SortOrder int32
}

func (q *Queries) CreateGalleryPhoto(ctx context.Context, arg CreateGalleryPhotoParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createGalleryPhoto, arg.PhotoUrl, arg.ThumbUrl, arg.SortOrder)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteGalleryPhoto = `-- name: DeleteGalleryPhoto :exec
DELETE FROM gallery_photos WHERE id = ?
`

func (q *Queries) DeleteGalleryPhoto(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteGalleryPhoto, id)
	return err
}

const getGalleryPhoto = `-- name: GetGalleryPhoto :one
SELECT id, photo_url, thumb_url, sort_order FROM gallery_photos WHERE id = ? LIMIT 1
`

func (q *Queries) GetGalleryPhoto(ctx context.Context, id uint64) (GalleryPhoto, error) {
	row := q.db.QueryRowContext(ctx, getGalleryPhoto, id)
	var i GalleryPhoto
	err := row.Scan(
		&i.ID,
		&i.PhotoUrl,
		&i.ThumbUrl,
		&i.SortOrder,
	)
	return i, err
}

const listGalleryPhotos = `-- name: ListGalleryPhotos :many
SELECT id, photo_url, thumb_url, sort_order FROM gallery_photos ORDER BY sort_order ASC
`

func (q *Queries) ListGalleryPhotos(ctx context.Context) ([]GalleryPhoto, error) {
	rows, err := q.db.QueryContext(ctx, listGalleryPhotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GalleryPhoto
	for rows.Next() {
		var i GalleryPhoto
		if err := rows.Scan(
			&i.ID,
			&i.PhotoUrl,
			&i.ThumbUrl,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGalleryPhoto = `-- name: UpdateGalleryPhoto :exec
UPDATE gallery_photos SET photo_url=?, thumb_url=?, sort_order=?
WHERE id = ?
`

type UpdateGalleryPhotoParams struct {
	PhotoUrl  string
	ThumbUrl  string
	SortOrder int32
	ID        uint64
}

func (q *Queries) UpdateGalleryPhoto(ctx context.Context, arg UpdateGalleryPhotoParams) error {
	_, err := q.db.ExecContext(ctx, updateGalleryPhoto,
		arg.PhotoUrl,
		arg.ThumbUrl,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
