// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation_content.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getInvitationContent = `-- name: GetInvitationContent :one
SELECT id, bride_name, bride_parents_text, bride_instagram, bride_photo_url, groom_name, groom_parents_text, groom_instagram, groom_photo_url, wedding_date, hashtag, cover_logo_url, cover_image_desktop_url, cover_image_mobile_url, quote_text, thanks_title, thanks_description, music_url, video_gallery_title, video_gallery_youtube_url, video_gallery_caption, live_streaming_title, live_streaming_youtube_url, instagram_filter_title, instagram_filter_caption, instagram_filter_preview_photo_url, instagram_filter_link, wedding_gift_description, dresscode_title, dresscode_description, dresscode_note, updated_at FROM invitation_content WHERE id = 1 LIMIT 1
`

func (q *Queries) GetInvitationContent(ctx context.Context) (InvitationContent, error) {
	row := q.db.QueryRowContext(ctx, getInvitationContent)
	var i InvitationContent
	err := row.Scan(
		&i.ID,
		&i.BrideName,
		&i.BrideParentsText,
		&i.BrideInstagram,
		&i.BridePhotoUrl,
		&i.GroomName,
		&i.GroomParentsText,
		&i.GroomInstagram,
		&i.GroomPhotoUrl,
		&i.WeddingDate,
		&i.Hashtag,
		&i.CoverLogoUrl,
		&i.CoverImageDesktopUrl,
		&i.CoverImageMobileUrl,
		&i.QuoteText,
		&i.ThanksTitle,
		&i.ThanksDescription,
		&i.MusicUrl,
		&i.VideoGalleryTitle,
		&i.VideoGalleryYoutubeUrl,
		&i.VideoGalleryCaption,
		&i.LiveStreamingTitle,
		&i.LiveStreamingYoutubeUrl,
		&i.InstagramFilterTitle,
		&i.InstagramFilterCaption,
		&i.InstagramFilterPreviewPhotoUrl,
		&i.InstagramFilterLink,
		&i.WeddingGiftDescription,
		&i.DresscodeTitle,
		&i.DresscodeDescription,
		&i.DresscodeNote,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvitationContent = `-- name: UpdateInvitationContent :exec
UPDATE invitation_content SET
  bride_name = ?, bride_parents_text = ?, bride_instagram = ?, bride_photo_url = ?,
  groom_name = ?, groom_parents_text = ?, groom_instagram = ?, groom_photo_url = ?,
  wedding_date = ?, hashtag = ?,
  cover_logo_url = ?, cover_image_desktop_url = ?, cover_image_mobile_url = ?,
  quote_text = ?,
  thanks_title = ?, thanks_description = ?,
  music_url = ?,
  video_gallery_title = ?, video_gallery_youtube_url = ?, video_gallery_caption = ?,
  live_streaming_title = ?, live_streaming_youtube_url = ?,
  instagram_filter_title = ?, instagram_filter_caption = ?, instagram_filter_preview_photo_url = ?, instagram_filter_link = ?,
  wedding_gift_description = ?,
  dresscode_title = ?, dresscode_description = ?, dresscode_note = ?
WHERE id = 1
`

type UpdateInvitationContentParams struct {
	BrideName                      string
	BrideParentsText               sql.NullString
	BrideInstagram                 string
	BridePhotoUrl                  string
	GroomName                      string
	GroomParentsText               sql.NullString
	GroomInstagram                 string
	GroomPhotoUrl                  string
	WeddingDate                    time.Time
	Hashtag                        string
	CoverLogoUrl                   string
	CoverImageDesktopUrl           string
	CoverImageMobileUrl            string
	QuoteText                      sql.NullString
	ThanksTitle                    string
	ThanksDescription              sql.NullString
	MusicUrl                       string
	VideoGalleryTitle              string
	VideoGalleryYoutubeUrl         string
	VideoGalleryCaption            string
	LiveStreamingTitle             string
	LiveStreamingYoutubeUrl        string
	InstagramFilterTitle           string
	InstagramFilterCaption         sql.NullString
	InstagramFilterPreviewPhotoUrl string
	InstagramFilterLink            string
	WeddingGiftDescription         sql.NullString
	DresscodeTitle                 string
	DresscodeDescription           sql.NullString
	DresscodeNote                  sql.NullString
}

func (q *Queries) UpdateInvitationContent(ctx context.Context, arg UpdateInvitationContentParams) error {
	_, err := q.db.ExecContext(ctx, updateInvitationContent,
		arg.BrideName,
		arg.BrideParentsText,
		arg.BrideInstagram,
		arg.BridePhotoUrl,
		arg.GroomName,
		arg.GroomParentsText,
		arg.GroomInstagram,
		arg.GroomPhotoUrl,
		arg.WeddingDate,
		arg.Hashtag,
		arg.CoverLogoUrl,
		arg.CoverImageDesktopUrl,
		arg.CoverImageMobileUrl,
		arg.QuoteText,
		arg.ThanksTitle,
		arg.ThanksDescription,
		arg.MusicUrl,
		arg.VideoGalleryTitle,
		arg.VideoGalleryYoutubeUrl,
		arg.VideoGalleryCaption,
		arg.LiveStreamingTitle,
		arg.LiveStreamingYoutubeUrl,
		arg.InstagramFilterTitle,
		arg.InstagramFilterCaption,
		arg.InstagramFilterPreviewPhotoUrl,
		arg.InstagramFilterLink,
		arg.WeddingGiftDescription,
		arg.DresscodeTitle,
		arg.DresscodeDescription,
		arg.DresscodeNote,
	)
	return err
}
