// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: love_story_chapters.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createLoveStoryChapter = `-- name: CreateLoveStoryChapter :execlastid
INSERT INTO love_story_chapters (photo_url, title, caption, sort_order)
VALUES (?, ?, ?, ?)
`

type CreateLoveStoryChapterParams struct {
	PhotoUrl  string
	Title     string
	Caption   sql.NullString
	SortOrder int32
}

func (q *Queries) CreateLoveStoryChapter(ctx context.Context, arg CreateLoveStoryChapterParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createLoveStoryChapter,
		arg.PhotoUrl,
		arg.Title,
		arg.Caption,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteLoveStoryChapter = `-- name: DeleteLoveStoryChapter :exec
DELETE FROM love_story_chapters WHERE id = ?
`

func (q *Queries) DeleteLoveStoryChapter(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteLoveStoryChapter, id)
	return err
}

const getLoveStoryChapter = `-- name: GetLoveStoryChapter :one
SELECT id, photo_url, title, caption, sort_order FROM love_story_chapters WHERE id = ? LIMIT 1
`

func (q *Queries) GetLoveStoryChapter(ctx context.Context, id uint64) (LoveStoryChapter, error) {
	row := q.db.QueryRowContext(ctx, getLoveStoryChapter, id)
	var i LoveStoryChapter
	err := row.Scan(
		&i.ID,
		&i.PhotoUrl,
		&i.Title,
		&i.Caption,
		&i.SortOrder,
	)
	return i, err
}

const listLoveStoryChapters = `-- name: ListLoveStoryChapters :many
SELECT id, photo_url, title, caption, sort_order FROM love_story_chapters ORDER BY sort_order ASC
`

func (q *Queries) ListLoveStoryChapters(ctx context.Context) ([]LoveStoryChapter, error) {
	rows, err := q.db.QueryContext(ctx, listLoveStoryChapters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoveStoryChapter
	for rows.Next() {
		var i LoveStoryChapter
		if err := rows.Scan(
			&i.ID,
			&i.PhotoUrl,
			&i.Title,
			&i.Caption,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoveStoryChapter = `-- name: UpdateLoveStoryChapter :exec
UPDATE love_story_chapters SET photo_url=?, title=?, caption=?, sort_order=?
WHERE id = ?
`

type UpdateLoveStoryChapterParams struct {
	PhotoUrl  string
	Title     string
	Caption   sql.NullString
	SortOrder int32
	ID        uint64
}

func (q *Queries) UpdateLoveStoryChapter(ctx context.Context, arg UpdateLoveStoryChapterParams) error {
	_, err := q.db.ExecContext(ctx, updateLoveStoryChapter,
		arg.PhotoUrl,
		arg.Title,
		arg.Caption,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
