// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rundown_items.sql

package sqlc

import (
	"context"
)

const createRundownItem = `-- name: CreateRundownItem :execlastid
INSERT INTO rundown_items (group_label, time_label, activity_text, sort_order)
VALUES (?, ?, ?, ?)
`

type CreateRundownItemParams struct {
	GroupLabel   string
	TimeLabel    string
	ActivityText string
	SortOrder    int32
}

func (q *Queries) CreateRundownItem(ctx context.Context, arg CreateRundownItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createRundownItem,
		arg.GroupLabel,
		arg.TimeLabel,
		arg.ActivityText,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteRundownItem = `-- name: DeleteRundownItem :exec
DELETE FROM rundown_items WHERE id = ?
`

func (q *Queries) DeleteRundownItem(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteRundownItem, id)
	return err
}

const getRundownItem = `-- name: GetRundownItem :one
SELECT id, group_label, time_label, activity_text, sort_order FROM rundown_items WHERE id = ? LIMIT 1
`

func (q *Queries) GetRundownItem(ctx context.Context, id uint64) (RundownItem, error) {
	row := q.db.QueryRowContext(ctx, getRundownItem, id)
	var i RundownItem
	err := row.Scan(
		&i.ID,
		&i.GroupLabel,
		&i.TimeLabel,
		&i.ActivityText,
		&i.SortOrder,
	)
	return i, err
}

const listRundownItems = `-- name: ListRundownItems :many
SELECT id, group_label, time_label, activity_text, sort_order FROM rundown_items ORDER BY sort_order ASC
`

func (q *Queries) ListRundownItems(ctx context.Context) ([]RundownItem, error) {
	rows, err := q.db.QueryContext(ctx, listRundownItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RundownItem
	for rows.Next() {
		var i RundownItem
		if err := rows.Scan(
			&i.ID,
			&i.GroupLabel,
			&i.TimeLabel,
			&i.ActivityText,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRundownItem = `-- name: UpdateRundownItem :exec
UPDATE rundown_items SET group_label=?, time_label=?, activity_text=?, sort_order=?
WHERE id = ?
`

type UpdateRundownItemParams struct {
	GroupLabel   string
	TimeLabel    string
	ActivityText string
	SortOrder    int32
	ID           uint64
}

func (q *Queries) UpdateRundownItem(ctx context.Context, arg UpdateRundownItemParams) error {
	_, err := q.db.ExecContext(ctx, updateRundownItem,
		arg.GroupLabel,
		arg.TimeLabel,
		arg.ActivityText,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
