// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sections.sql

package sqlc

import (
	"context"
)

const getSectionByKey = `-- name: GetSectionByKey :one
SELECT id, section_key, label, is_enabled, sort_order FROM sections WHERE section_key = ? LIMIT 1
`

func (q *Queries) GetSectionByKey(ctx context.Context, sectionKey string) (Section, error) {
	row := q.db.QueryRowContext(ctx, getSectionByKey, sectionKey)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.SectionKey,
		&i.Label,
		&i.IsEnabled,
		&i.SortOrder,
	)
	return i, err
}

const listEnabledSections = `-- name: ListEnabledSections :many
SELECT id, section_key, label, is_enabled, sort_order FROM sections WHERE is_enabled = TRUE ORDER BY sort_order ASC
`

func (q *Queries) ListEnabledSections(ctx context.Context) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.SectionKey,
			&i.Label,
			&i.IsEnabled,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSections = `-- name: ListSections :many
SELECT id, section_key, label, is_enabled, sort_order FROM sections ORDER BY sort_order ASC
`

func (q *Queries) ListSections(ctx context.Context) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.SectionKey,
			&i.Label,
			&i.IsEnabled,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSection = `-- name: UpdateSection :exec
UPDATE sections SET label = ?, is_enabled = ?, sort_order = ?
WHERE section_key = ?
`

type UpdateSectionParams struct {
	Label      string
	IsEnabled  bool
	SortOrder  int32
	SectionKey string
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) error {
	_, err := q.db.ExecContext(ctx, updateSection,
		arg.Label,
		arg.IsEnabled,
		arg.SortOrder,
		arg.SectionKey,
	)
	return err
}
