// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wedding_gift_banks.sql

package sqlc

import (
	"context"
)

const createWeddingGiftBank = `-- name: CreateWeddingGiftBank :execlastid
INSERT INTO wedding_gift_banks (bank_name, account_number, account_name, sort_order)
VALUES (?, ?, ?, ?)
`

type CreateWeddingGiftBankParams struct {
	BankName      string
	AccountNumber string
	AccountName   string
	SortOrder     int32
}

func (q *Queries) CreateWeddingGiftBank(ctx context.Context, arg CreateWeddingGiftBankParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createWeddingGiftBank,
		arg.BankName,
		arg.AccountNumber,
		arg.AccountName,
		arg.SortOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteWeddingGiftBank = `-- name: DeleteWeddingGiftBank :exec
DELETE FROM wedding_gift_banks WHERE id = ?
`

func (q *Queries) DeleteWeddingGiftBank(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteWeddingGiftBank, id)
	return err
}

const getWeddingGiftBank = `-- name: GetWeddingGiftBank :one
SELECT id, bank_name, account_number, account_name, sort_order FROM wedding_gift_banks WHERE id = ? LIMIT 1
`

func (q *Queries) GetWeddingGiftBank(ctx context.Context, id uint64) (WeddingGiftBank, error) {
	row := q.db.QueryRowContext(ctx, getWeddingGiftBank, id)
	var i WeddingGiftBank
	err := row.Scan(
		&i.ID,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountName,
		&i.SortOrder,
	)
	return i, err
}

const listWeddingGiftBanks = `-- name: ListWeddingGiftBanks :many
SELECT id, bank_name, account_number, account_name, sort_order FROM wedding_gift_banks ORDER BY sort_order ASC
`

func (q *Queries) ListWeddingGiftBanks(ctx context.Context) ([]WeddingGiftBank, error) {
	rows, err := q.db.QueryContext(ctx, listWeddingGiftBanks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeddingGiftBank
	for rows.Next() {
		var i WeddingGiftBank
		if err := rows.Scan(
			&i.ID,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWeddingGiftBank = `-- name: UpdateWeddingGiftBank :exec
UPDATE wedding_gift_banks SET bank_name=?, account_number=?, account_name=?, sort_order=?
WHERE id = ?
`

type UpdateWeddingGiftBankParams struct {
	BankName      string
	AccountNumber string
	AccountName   string
	SortOrder     int32
	ID            uint64
}

func (q *Queries) UpdateWeddingGiftBank(ctx context.Context, arg UpdateWeddingGiftBankParams) error {
	_, err := q.db.ExecContext(ctx, updateWeddingGiftBank,
		arg.BankName,
		arg.AccountNumber,
		arg.AccountName,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
