// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_users.sql

package sqlc

import (
	"context"
	"time"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :execlastid
INSERT INTO admin_users (username, password_hash) VALUES (?, ?)
`

type CreateAdminUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAdminUser, arg.Username, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteAdminUser = `-- name: DeleteAdminUser :exec
DELETE FROM admin_users WHERE id = ?
`

func (q *Queries) DeleteAdminUser(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteAdminUser, id)
	return err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, password_hash, created_at FROM admin_users WHERE username = ? LIMIT 1
`

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, username, created_at FROM admin_users ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAdminUsersParams struct {
	Limit  int32
	Offset int32
}

type ListAdminUsersRow struct {
	ID        uint64
	Username  string
	CreatedAt time.Time
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]ListAdminUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminUsersRow
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminUserUsername = `-- name: UpdateAdminUserUsername :exec
UPDATE admin_users SET username = ? WHERE id = ?
`

type UpdateAdminUserUsernameParams struct {
	Username string
	ID       uint64
}

func (q *Queries) UpdateAdminUserUsername(ctx context.Context, arg UpdateAdminUserUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminUserUsername, arg.Username, arg.ID)
	return err
}

const updateAdminUserUsernameAndPassword = `-- name: UpdateAdminUserUsernameAndPassword :exec
UPDATE admin_users SET username = ?, password_hash = ? WHERE id = ?
`

type UpdateAdminUserUsernameAndPasswordParams struct {
	Username     string
	PasswordHash string
	ID           uint64
}

func (q *Queries) UpdateAdminUserUsernameAndPassword(ctx context.Context, arg UpdateAdminUserUsernameAndPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminUserUsernameAndPassword, arg.Username, arg.PasswordHash, arg.ID)
	return err
}
