// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type GuestsGender string

const (
	GuestsGenderMale   GuestsGender = "male"
	GuestsGenderFemale GuestsGender = "female"
)

func (e *GuestsGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GuestsGender(s)
	case string:
		*e = GuestsGender(s)
	default:
		return fmt.Errorf("unsupported scan type for GuestsGender: %T", src)
	}
	return nil
}

type NullGuestsGender struct {
	GuestsGender GuestsGender
	Valid        bool // Valid is true if GuestsGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGuestsGender) Scan(value interface{}) error {
	if value == nil {
		ns.GuestsGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GuestsGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGuestsGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GuestsGender), nil
}

type GuestsInvitationType string

const (
	GuestsInvitationTypeOnline   GuestsInvitationType = "online"
	GuestsInvitationTypePhysical GuestsInvitationType = "physical"
)

func (e *GuestsInvitationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GuestsInvitationType(s)
	case string:
		*e = GuestsInvitationType(s)
	default:
		return fmt.Errorf("unsupported scan type for GuestsInvitationType: %T", src)
	}
	return nil
}

type NullGuestsInvitationType struct {
	GuestsInvitationType GuestsInvitationType
	Valid                bool // Valid is true if GuestsInvitationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGuestsInvitationType) Scan(value interface{}) error {
	if value == nil {
		ns.GuestsInvitationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GuestsInvitationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGuestsInvitationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GuestsInvitationType), nil
}

type GuestsRsvpStatus string

const (
	GuestsRsvpStatusPending      GuestsRsvpStatus = "pending"
	GuestsRsvpStatusAttending    GuestsRsvpStatus = "attending"
	GuestsRsvpStatusNotAttending GuestsRsvpStatus = "not_attending"
	GuestsRsvpStatusRemindLater  GuestsRsvpStatus = "remind_later"
)

func (e *GuestsRsvpStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GuestsRsvpStatus(s)
	case string:
		*e = GuestsRsvpStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GuestsRsvpStatus: %T", src)
	}
	return nil
}

type NullGuestsRsvpStatus struct {
	GuestsRsvpStatus GuestsRsvpStatus
	Valid            bool // Valid is true if GuestsRsvpStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGuestsRsvpStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GuestsRsvpStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GuestsRsvpStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGuestsRsvpStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GuestsRsvpStatus), nil
}

type GuestsSide string

const (
	GuestsSideGroom GuestsSide = "groom"
	GuestsSideBride GuestsSide = "bride"
)

func (e *GuestsSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GuestsSide(s)
	case string:
		*e = GuestsSide(s)
	default:
		return fmt.Errorf("unsupported scan type for GuestsSide: %T", src)
	}
	return nil
}

type NullGuestsSide struct {
	GuestsSide GuestsSide
	Valid      bool // Valid is true if GuestsSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGuestsSide) Scan(value interface{}) error {
	if value == nil {
		ns.GuestsSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GuestsSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGuestsSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GuestsSide), nil
}

type GuestsSouvenirType string

const (
	GuestsSouvenirTypeRegular GuestsSouvenirType = "regular"
	GuestsSouvenirTypeVip     GuestsSouvenirType = "vip"
)

func (e *GuestsSouvenirType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GuestsSouvenirType(s)
	case string:
		*e = GuestsSouvenirType(s)
	default:
		return fmt.Errorf("unsupported scan type for GuestsSouvenirType: %T", src)
	}
	return nil
}

type NullGuestsSouvenirType struct {
	GuestsSouvenirType GuestsSouvenirType
	Valid              bool // Valid is true if GuestsSouvenirType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGuestsSouvenirType) Scan(value interface{}) error {
	if value == nil {
		ns.GuestsSouvenirType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GuestsSouvenirType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGuestsSouvenirType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GuestsSouvenirType), nil
}

type WhatsappSendLogsStatus string

const (
	WhatsappSendLogsStatusPending WhatsappSendLogsStatus = "pending"
	WhatsappSendLogsStatusSent    WhatsappSendLogsStatus = "sent"
	WhatsappSendLogsStatusFailed  WhatsappSendLogsStatus = "failed"
)

func (e *WhatsappSendLogsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WhatsappSendLogsStatus(s)
	case string:
		*e = WhatsappSendLogsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WhatsappSendLogsStatus: %T", src)
	}
	return nil
}

type NullWhatsappSendLogsStatus struct {
	WhatsappSendLogsStatus WhatsappSendLogsStatus
	Valid                  bool // Valid is true if WhatsappSendLogsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWhatsappSendLogsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WhatsappSendLogsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WhatsappSendLogsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWhatsappSendLogsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WhatsappSendLogsStatus), nil
}

type AdminUser struct {
	ID           uint64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}

type AgendaEvent struct {
	ID           uint64
	EventLabel   string
	TimeLabel    string
	VenueName    string
	VenueAddress sql.NullString
	City         string
	MapsUrl      string
	SortOrder    int32
}

type GalleryPhoto struct {
	ID        uint64
	PhotoUrl  string
	ThumbUrl  string
	SortOrder int32
}

type Guest struct {
	ID                  uint64
	Name                string
	Phone               string
	Side                GuestsSide
	Token               string
	RsvpStatus          GuestsRsvpStatus
	RsvpRespondedAt     sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Gender              NullGuestsGender
	InvitationType      GuestsInvitationType
	SouvenirType        GuestsSouvenirType
	Email               string
	Address             sql.NullString
	Notes               sql.NullString
	AttendingCount      uint8
	IsExpectedAttending bool
}

type InvitationContent struct {
	ID                             uint64
	BrideName                      string
	BrideParentsText               sql.NullString
	BrideInstagram                 string
	BridePhotoUrl                  string
	GroomName                      string
	GroomParentsText               sql.NullString
	GroomInstagram                 string
	GroomPhotoUrl                  string
	WeddingDate                    time.Time
	Hashtag                        string
	CoverLogoUrl                   string
	CoverImageDesktopUrl           string
	CoverImageMobileUrl            string
	QuoteText                      sql.NullString
	ThanksTitle                    string
	ThanksDescription              sql.NullString
	MusicUrl                       string
	VideoGalleryTitle              string
	VideoGalleryYoutubeUrl         string
	VideoGalleryCaption            string
	LiveStreamingTitle             string
	LiveStreamingYoutubeUrl        string
	InstagramFilterTitle           string
	InstagramFilterCaption         sql.NullString
	InstagramFilterPreviewPhotoUrl string
	InstagramFilterLink            string
	WeddingGiftDescription         sql.NullString
	DresscodeTitle                 string
	DresscodeDescription           sql.NullString
	DresscodeNote                  sql.NullString
	UpdatedAt                      time.Time
	DresscodeImageUrl              string
	ShareImageUrl                  string
}

type LoveStoryChapter struct {
	ID        uint64
	PhotoUrl  string
	Title     string
	Caption   sql.NullString
	SortOrder int32
}

type RundownItem struct {
	ID           uint64
	GroupLabel   string
	TimeLabel    string
	ActivityText string
	SortOrder    int32
}

type Section struct {
	ID         uint64
	SectionKey string
	Label      string
	IsEnabled  bool
	SortOrder  int32
}

type WeddingGiftBank struct {
	ID            uint64
	BankName      string
	AccountNumber string
	AccountName   string
	SortOrder     int32
}

type WhatsappConfig struct {
	ID                 uint64
	MessageTemplate    string
	IsEnabled          bool
	UpdatedAt          time.Time
	InvitationTemplate string
}

type WhatsappSendLog struct {
	ID             uint64
	GuestID        uint64
	GuestName      string
	Phone          string
	QrPayload      string
	CoupleName     string
	EventDateLabel string
	Status         WhatsappSendLogsStatus
	ErrorMessage   sql.NullString
	SentAt         sql.NullTime
	CreatedAt      time.Time
	AttendingCount uint8
}
